### ISSUE TITLE
Allow users to subscribe to identity_connected, identity_disconnected and CLI SQL events

### ISSUE THREAD

**Issue by jdetter** [clockworklabs/com.clockworklabs.spacetimedbsdk#102]
We currently don't support allowing clients to subscribe to the connect/disconnect reducers and we also don't support allowing clients to subscribe to arbitrary CLI SQL events (like running `spacetime sql <module> "INSERT INTO <table-name> <values>"`). We should implement callbacks for these events.

We started suppressing these errors in this PR: https://github.com/clockworklabs/SpacetimeDB/pull/1461

See implementation notes pointed out by Phoebe: <https://github.com/orgs/clockworklabs/projects/22/views/16?filterQuery=priority%3AP1+builtin&pane=issue&itemId=67001837>

**Comment by bfops** [comment]
Is this just for the C#/Unity SDK, or do we have this gap in all SDKs?
