### ISSUE TITLE
Rename UnityNetworkManager to SpacetimeDBNetworkManager

### ISSUE THREAD

**Issue by jdetter** [clockworklabs/com.clockworklabs.spacetimedbsdk#135]
`UnityNetworkManager` is too general and could possibly conflict with other packages that have network managers.

*Technically* this may not be an API break because Unity references scripts by an ID instead of their name, but this needs to be updated before we do tutorials or documentation or anything else that would reference the name of this script.

**Comment by RReverser** [comment]
> `UnityNetworkManager` is too general and could possibly conflict with other packages that have network managers.

Doesn't Unity support namespacing? I'd think `SpacetimeDB.Types.UnityNetworkManager` (or `UserNamespace.UnityNetworkManager` if generated with custom namespace) would be always distinct from ones coming from other packages?
